### PR TITLE
Now it assembling properly

### PR DESCRIPTION
**Pull request by Warezovvv**
Try to compile now on your machine. Will it work?) 
What is happening with Release Debug names? :D

### CODE REVIEW

**Comment by Warezovvv** [comment]
I formatted my full repository and got pretty strange things :) 
1) pragma Singleton  - was removed
2) readonly property => property
I know it's problems of qmljs but WTF? Why is it deleting this?) Do you have this problems too?

**Comment by Warezovvv** [comment]
https://bugreports.qt.io/browse/QTCREATORBUG-15745 about 2nd

**Comment by Warezovvv** [comment]
May be should update to 4.0? will it still work if download 4.0.0 version?

**Comment by jesperhh** [comment]
I haven't actually used the application after I finished developing it :-) But I will see if I can set up an automated build against the newest version of Qt Creator today or tomorrow.

**Comment by Warezovvv** [comment]
Okay, thanks. Awesome)
BTW, your tool is one of a kind, it's really really rare, so it can be really cool, when will work with Qt Creator 4))

**Pull request merged**
